### ISSUE TITLE
Add fonts to the editor

### ISSUE THREAD

**Issue by soderlind** [WPTT/webfont-loader#3]
This works, at least for the classic editor
```php
// Register Editor Stylesheet
function text_domain_add_editor_styles() {
    // Easily add a Google Font to the Editor
    $font_url = str_replace( ',', '%2C', 'https://fonts.googleapis.com/css?family=Indie+Flower' );
    add_editor_style( $font_url );
    add_editor_style('editor-styles.css');
}
add_action('admin_init', 'text_domain_add_editor_styles');
```

But I can't get this to work:
```php
function text_domain_add_editor_styles() {
    // Easily add a Google Font to the Editor
    $font_url = str_replace( ',', '%2C', 'https://fonts.googleapis.com/css?family=Indie+Flower' );
    add_editor_style( wptt_get_webfont_styles( $font_url ) ); // THIS FAILS
    add_editor_style('editor-styles.css');
}
add_action('admin_init', 'text_domain_add_editor_styles');
```
**EDIT**: After looking at the source I see why, `wptt_get_webfont_styles` returns the stylesheet content, but `add_editor_style` require the url to the stylesheet. Why does wptt_get_webfont_styles inline the stylesheet for the font? Wouldn't it be better if it pointed to a stylesheet in `WP_CONTENT_DIR . '/fonts'` ?

**Comment by aristath** [comment]
Are you trying to add styles to tinyMCE? 
If that is the case, then you could use the `tiny_mce_before_init` filter (see example on https://developer.wordpress.org/reference/functions/add_editor_style/#comment-1739)

> Wouldn't it be better if it pointed to a stylesheet in `WP_CONTENT_DIR . '/fonts'` ?

Writing a stylesheet is something I'm currently working on. There are many things to consider and it gets a bit complicated because of multisites and the fact that some sites may use the same font-family but different weights for example, so the CSS would be different and we can't name the CSS files as `wp-content/fonts/{$family}.css`. An alternative approach I'm currently working on is to hash the URL using `md5()` and then use that as the css filename to ensure it's unique, but that still needs some work before I am satisfied it will work properly under all circumstances and servers.

**Comment by soderlind** [comment]
> it gets a bit complicated because of multisites

I'm responsible for a multisite (100+ subsites), we're defiantly using different fonts and/or fonts sizes, but luckily only three homegrown themes they can choose between. "Homegrown" as in developed by the WordPress VIP partner Dekode.

**Comment by aristath** [comment]
The implementation was completely refactored and you can now use a `wptt_get_webfont_url` function to get a locally-hosted instance of the CSS.
More info is available on the [README](https://github.com/WPTT/webfont-loader/blob/master/README.md) file.

**Comment by soderlind** [comment]
Excellent, thank you :)
